apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gy3l
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0024-tenant/tkrw-pr712-0075-0024-app/devfile-sample-gy3l@sha256:a4f0aefd56414d1d333665d18d79644ef872aac437d8caa489ad8a5fd5a74807
        name: my-nodejs
        resources: {}
status: {}
